server.port=8082

spring.application.name=grading-service

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/etudiants_db
spring.datasource.username=etudiants_user
spring.datasource.password=etudiants_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.etudiants.grading=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG